name: e2e
on:
  - push
  - pull_request
jobs:
  prometheus:
    runs-on: ubuntu-latest
    name: prometheus tests
    steps:
    - uses: actions/checkout@v2
    - name: Start KinD
      uses: engineerd/setup-kind@v0.4.0
      with:
        version: v0.8.1
        image: kindest/node:v1.18.8
    - name: Check cluster
      run: |
        kubectl cluster-info
        kubectl get pods -A
    - name: Build and load images
      run: |
        export SHELL=/bin/bash
        make build image
        kind load docker-image quay.io/prometheus-operator/prometheus-operator:$(git rev-parse --short HEAD)
        kind load docker-image quay.io/prometheus-operator/prometheus-config-reloader:$(git rev-parse --short HEAD)
        kubectl apply -f scripts/minikube-rbac.yaml
    - name: Run tests
      run:
        EXCLUDE_ALERTMANAGER_TESTS=true EXCLUDE_THANOS_TESTS=true make test-e2e
  alertmanager:
    runs-on: ubuntu-latest
    name: alertmanager tests
    steps:
    - uses: actions/checkout@v2
    - name: Start KinD
      uses: engineerd/setup-kind@v0.4.0
      with:
        version: v0.8.1
        image: kindest/node:v1.18.8
    - name: Check cluster
      run: |
        kubectl cluster-info
        kubectl get pods -A
    - name: Build and load images
      run: |
        export SHELL=/bin/bash
        make build image
        kind load docker-image quay.io/prometheus-operator/prometheus-operator:$(git rev-parse --short HEAD)
        kind load docker-image quay.io/prometheus-operator/prometheus-config-reloader:$(git rev-parse --short HEAD)
        kubectl apply -f scripts/minikube-rbac.yaml
    - name: Run tests
      run:
        EXCLUDE_PROMETHEUS_TESTS=true EXCLUDE_THANOS_TESTS=true make test-e2e
  thanosruler:
    runs-on: ubuntu-latest
    name: thanos ruler tests
    steps:
    - uses: actions/checkout@v2
    - name: Start KinD
      uses: engineerd/setup-kind@v0.4.0
      with:
        version: v0.8.1
        image: kindest/node:v1.18.8
    - name: Check cluster
      run: |
        kubectl cluster-info
        kubectl get pods -A
    - name: Build and load images
      run: |
        export SHELL=/bin/bash
        make build image
        kind load docker-image quay.io/prometheus-operator/prometheus-operator:$(git rev-parse --short HEAD)
        kind load docker-image quay.io/prometheus-operator/prometheus-config-reloader:$(git rev-parse --short HEAD)
        kubectl apply -f scripts/minikube-rbac.yaml
    - name: Run tests
      run:
        EXCLUDE_ALERTMANAGER_TESTS=true EXCLUDE_PROMETHEUS_TESTS=true make test-e2e
